### ISSUE TITLE
Broken (& missing) files

### ISSUE THREAD

**Issue by CastellanLiu** [rongduo/photorealistic_inrinsic_dataset#1]
I've downloaded your data from Baidu Yun Drive and Dropbox, both of the zipped files show that `resized_data\diffuse-resize\02069488.diffuse-resize.png` and `resized_data\diffuse-resize\02086566.diffuse-resize.png` are broken.
The number of files in the other three folders is 21,478, but in the `diffuse-resize` folder, it is 21,476. The aforementioned two images are missing.

**Comment by rongduo** [comment]
Hi @CastellanLiu, thanks for pointing this out.  
I checked the number of files and each sub-folder contains 21,478 images. 
Unfortunately, the two images you mentioned above are broken within the compression process. 
I will prepare a new zip file. 
You can also throw an email to me to get the missing files quickly.
